In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Loading Dataset

In [76]:
edata = pd.read_csv("EV_DATASET.csv")

In [77]:
edata.head()

,Name,Capacity of the Battery in Ampere Hour,Remaining Battery Percentage,SPEED,Driving Range in KM
0,e2o Plus P2,280.0,100.0,80,140.0
1,e2o Plus P4,210.0,100.0,80,110.0
2,e2o Plus P6,210.0,100.0,80,110.0
3,e2o Plus P2,280.0,100.0,80,140.0
4,eVerito C2,189.0,100.0,80,110.0

In [78]:
edata.tail()

,Name,Capacity of the Battery in Ampere Hour,Remaining Battery Percentage,SPEED,Driving Range in KM
29,MAHINDRA TREO - HRT,154.0,55.0,78,60.0
30,MAHINDRA TREO - SFT,154.0,10.0,78,20.0
31,MAHINDRA TREO YAARI - HRT,77.0,90.0,78,75.0
32,MAHINDRA TREO YAARI - SFT,77.0,50.0,78,50.0
33,MAHINDRA TREO YAARI - SFT,77.0,19.0,78,30.0

In [79]:
edata["Name"].unique()
edata["Driving Range in KM"].unique()

array([140., 110., 130.,  85., 120., 100.,  80.,  60.,  90.,  70.,  55.,
        50.,  nan,  20.,  75.,  30.])

In [80]:
edata.dropna(inplace= True)
edata

,Name,Capacity of the Battery in Ampere Hour,Remaining Battery Percentage,SPEED,Driving Range in KM
0,e2o Plus P2,280.0,100.0,80,140.0
1,e2o Plus P4,210.0,100.0,80,110.0
2,e2o Plus P6,210.0,100.0,80,110.0
3,e2o Plus P2,280.0,100.0,80,140.0
4,eVerito C2,189.0,100.0,80,110.0
5,eVerito D2,252.0,100.0,80,140.0
6,eVerito D4,252.0,100.0,80,140.0
7,eVerito D6,252.0,100.0,80,140.0
8,eVerito C2,189.0,100.0,80,110.0
9,eVerito D2,252.0,100.0,80,140.0
10,eVerito D4,252.0,100.0,80,140.0
11,eVerito D6,252.0,100.0,80,140.0
13,MAHINDRA TREO - HRT,154.0,100.0,80,130.0
14,MAHINDRA TREO YAARI - SFT,77.0,100.0,80,85.0
15,MAHINDRA TREO YAARI - HRT,77.0,100.0,80,85.0
16,e2o Plus P2,280.0,90.0,80,120.0
17,e2o Plus P2,280.0,83.0,79,110.0
18,e2o Plus P2,280.0,75.0,75,100.0
19,e2o Plus P2,280.0,55.0,78,80.0
22,e2o Plus P4,210.0,60.0,70,70.0
23,e2o Plus P6,210.0,30.0,80,55.0
24,eVerito D4,252.0,80.0,80,100.0
25,eVerito D2,252.0,70.0,78,85.0
26,eVerito D6,252.0,40.0,78,50.0
28,MAHINDRA TREO - HRT,154.0,70.0,78,100.0
29,MAHINDRA TREO - HRT,154.0,55.0,78,60.0
30,MAHINDRA TREO - SFT,154.0,10.0,78,20.0
31,MAHINDRA TREO YAARI - HRT,77.0,90.0,78,75.0
32,MAHINDRA TREO YAARI - SFT,77.0,50.0,78,50.0
33,MAHINDRA TREO YAARI - SFT,77.0,19.0,78,30.0

## Using Multivariate Linear Regression

In [81]:
from sklearn import linear_model

In [82]:
edata_train = edata[0:33:2]
edata_test = edata[0:33:5]

edata_train

,Name,Capacity of the Battery in Ampere Hour,Remaining Battery Percentage,SPEED,Driving Range in KM
0,e2o Plus P2,280.0,100.0,80,140.0
2,e2o Plus P6,210.0,100.0,80,110.0
4,eVerito C2,189.0,100.0,80,110.0
6,eVerito D4,252.0,100.0,80,140.0
8,eVerito C2,189.0,100.0,80,110.0
10,eVerito D4,252.0,100.0,80,140.0
13,MAHINDRA TREO - HRT,154.0,100.0,80,130.0
15,MAHINDRA TREO YAARI - HRT,77.0,100.0,80,85.0
17,e2o Plus P2,280.0,83.0,79,110.0
19,e2o Plus P2,280.0,55.0,78,80.0
23,e2o Plus P6,210.0,30.0,80,55.0
25,eVerito D2,252.0,70.0,78,85.0
28,MAHINDRA TREO - HRT,154.0,70.0,78,100.0
30,MAHINDRA TREO - SFT,154.0,10.0,78,20.0
32,MAHINDRA TREO YAARI - SFT,77.0,50.0,78,50.0

In [83]:
result = linear_model.LinearRegression()
result_fit =result.fit(edata_train[['Capacity of the Battery in Ampere Hour','Remaining Battery Percentage','SPEED']],edata_train['Driving Range in KM'])

In [84]:
result.coef_  # forecast = coef1* capacity + coef2*remaining battery + coef3*SPEED +intercept

array([0.16764844, 0.98516513, 1.47388882])

In [85]:
result.intercept_

-129.5165647707638

In [89]:
import warnings
warnings.filterwarnings('ignore')

In [90]:
edata_test['Forecast'] = result.predict(edata_test[['Capacity of the Battery in Ampere Hour','Remaining Battery Percentage','SPEED']])

In [96]:
edata_test['Actual'] = edata_test['Driving Range in KM']

In [97]:
edata_test

,Name,Capacity of the Battery in Ampere Hour,Remaining Battery Percentage,SPEED,Driving Range in KM,Forecast,Actual
0,e2o Plus P2,280.0,100.0,80,140.0,133.852616,140.0
5,eVerito D2,252.0,100.0,80,140.0,129.158460,140.0
10,eVerito D4,252.0,100.0,80,140.0,129.158460,140.0
16,e2o Plus P2,280.0,90.0,80,120.0,124.000965,120.0
23,e2o Plus P6,210.0,30.0,80,55.0,53.155666,55.0
29,MAHINDRA TREO - HRT,154.0,55.0,78,60.0,65.448705,60.0

 ## ACCURACY USING Mean Squared Error

In [104]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score

error = np.sqrt(mean_squared_error(edata_test['Actual'],edata_test['Forecast']))

In [106]:
Percentage_Accuracy = 100 - error
Percentage_Accuracy

92.67463324802337